version: '3'
services:
  api:
    build: .
    ports:
    - "8000:80"
    links:
    - db
    environment:
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
      DB_HOST: db
      DEBUG_LEVEL: trace
    depends_on:
    - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  frontend:
    build: ../frontend
    ports:
    - "8080:80"
    environment:
      API_ROOT: "http://localhost:8000/api"
